const express=require("express")
const cors=require("cors")
const moviesRouter=require('./routers/moviesRouter')
const userRouter=require('./routers/usersRouter')
const authRouter=require('./routers/authRouter')
const membersRouter=require('./routers/membersRouter')
const subscriptionsRouter=require('./routers/subscriptionsRouter')
const app=express()
app.use(cors())
require('./config/database')
app.use(express.json())
app.use('/api/movies',moviesRouter)
app.use('/api/user',userRouter)
app.use('/api/auth',authRouter)
app.use('/api/member',membersRouter)
app.use('/api/subs',subscriptionsRouter)
app.listen(8000)
console.log("server is running...")